name: Java CI

on: 
  push:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Use local my-action  
        uses: ./.github/Parcer/XmlParcer 
      - name:  Setup Java JDK
      - uses: actions/setup-java@v1.3.0
        with:
          java-version: 1.8
          java-package: jdk
      - name: Build with Maven
        run: mvn -B package -f pom.xml

 
     



  
  
