name: Java CI

on: 
  push:
    branches: 
      - master

jobs:
  my_job:
    name: deploy to staging
    runs-on: ubuntu-18.04
    
    
    steps:
    - uses: actions/checkout@v2
    - name:  Setup Java JDK
      uses: actions/setup-java@v1.3.0
      with:
        java-version: 1.8
        java-package: jdk  
    - name: Build with Maven
      run: mvn deploy
 
     



  
  
